### PR TITLE
Add Google Scholar parser

### PR DESCRIPTION
**Pull request by Cnly**
A simple one.

### CODE REVIEW

**Comment by alanzchen** [comment]
Your test is not being excuted by CI. Specify your test in `.travis.yml`.

Good job!

**Comment by Yexiaoxing** [comment]
Push the commits to master branch

**Comment by Yexiaoxing** [comment]
Pull from upstream and fix the conflict.

**Comment by Cnly** [comment]
It seems that Travis is forbidden from accessing Google... : /

**Comment by alanzchen** [comment]
Resolved #9

**Pull request merged**
